language: node_js
node_js: 
 - 8

before_script:
 - npm install

script:
 - npm run build

cache:
  directories:
    - "node_modules"

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  skip_cleanup: true
  file: build/*
  on:
    tags: true